pollingFrequencySeconds: 10

consensus:
  enabled: true
  url: "http://localhost:5053"
  name: "consensus-client"
execution:
  enabled: true
  url: "http://localhost:8545"
  name: "execution-client"
diskUsage:
  enabled: true
  directories:
  - /data/ethereum