pollingFrequencySeconds: 10

consensus:
  enabled: true
  url: "http://localhost:5053"
  name: "consensus-client"
execution:
  enabled: true
  url: "http://localhost:8545"
  name: "execution-client"
  modules:
  - "eth"
  - "net"
diskUsage:
  enabled: false
  directories:
  - /data/ethereum